stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    outs:
    - data/raw_data
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw_data/data.csv
    - src/data_preprocessing.py
    outs:
    - data/preprocess_data
  model_building:
    cmd: python src/model_building.py
    deps:
    - data/preprocess_data
    - src/model_building.py
    outs:
    - model
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - model/rf_model.pkl
    - src/model_evaluation.py
params:
- dvclive/params.yaml
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
