stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
    - src/data_ingestion.py
    # params:
    # - data_ingestion.test_size
    outs:
    - data/raw_data
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
    - data/raw_data/data.csv
    - src/data_preprocessing.py
    outs:
    - data/preprocess_data
  model_building:
    cmd: python src/model_building.py
    deps:
    # - data/processed_data
    - src/model_building.py
    # params:
    # - model_building.n_estimators
    # - model_building.random_state
    outs:
    - model
  model_evaluation:
    cmd: python src/model_evaluation.py
    deps:
    - model/rf_model.pkl
    - src/model_evaluation.py
params:
- dvclive/params.yaml
metrics:
- dvclive/model/evaluation_metrics/metrics.json
plots:
- dvclive/plots/metrics:
    x: step